name: "KubePodCrashLooping"
description: "Kubernetes pod crash loop monitoring"

log_file: "/var/log/kubernetes/pods.log"

# Elasticsearch configuration for Kubernetes pod monitoring
elasticsearch:
  index_pattern: "logs-*"
  scan_limit: 1000
  time_range_min: 15
  namespace_filter: ""  # Monitor all namespaces

# Log patterns for pod crash issues
log_patterns:
  - pattern: "CrashLoopBackOff"
    description: "Pod in crash loop state"
  - pattern: "ImagePullBackOff"
    description: "Image pull failures"
  - pattern: "OOMKilled"
    description: "Out of memory killed"
  - pattern: "Failed to start container"
    description: "Container start failures"
  - pattern: "Error: ErrImagePull"
    description: "Image pull errors"
  - pattern: "Liveness probe failed"
    description: "Liveness probe failures"
  - pattern: "Readiness probe failed"
    description: "Readiness probe failures"

# Metrics for pod health monitoring
metrics:
  - name: "PodRestartRate"
    query_tpl: "rate(kube_pod_container_status_restarts_total[5m])"
    operator: ">"
    threshold: 0.1
    weight: 10
    description: "High pod restart rate"
    
  - name: "PodMemoryUsage"
    query_tpl: "container_memory_usage_bytes{container!=\"POD\",container!=\"\"}"
    operator: ">"
    threshold: 536870912.0  # 512MB
    weight: 7
    description: "High memory usage"
    
  - name: "PodCPUThrottling"
    query_tpl: "rate(container_cpu_cfs_throttled_seconds_total[5m])"
    operator: ">"
    threshold: 0.25
    weight: 8
    description: "High CPU throttling rate"
    
  - name: "PodDiskUsage"
    query_tpl: "container_fs_usage_bytes{container!=\"POD\"}"
    operator: ">"
    threshold: 1073741824.0  # 1GB
    weight: 6
    description: "High disk usage"