log_file: /var/log/syslog
log_patterns:
  # System patterns that will trigger frequently
  - label: "systemd_service"
    regex: "systemd\\[1\\]: Starting"
  - label: "systemd_finished"
    regex: "systemd\\[1\\]: Finished"
  - label: "kernel_warning"
    regex: "kernel:.*hogged CPU"
  - label: "cron_job"
    regex: "CRON\\[\\d+\\]:"
  - label: "network_change"
    regex: "avahi-daemon.*address record"
  # Error patterns for monitoring
  - label: "authentication_failure"
    regex: "authentication failure"
  - label: "sudo_failure"
    regex: "sudo:.*authentication failure"
  - label: "ssh_failure"
    regex: "sshd.*Failed password"
  - label: "disk_error"
    regex: "(?i)disk.*error|I/O error"
  - label: "out_of_memory"
    regex: "Out of memory|OOM"
  - label: "segfault"
    regex: "segfault"
  - label: "kernel_panic"
    regex: "kernel panic"
  - label: "service_failed"
    regex: "systemd\\[1\\]:.*failed"

metrics:
  - name: "RAMUsage"
    query_tpl: "node_memory_Active_bytes"
    operator: ">"
    threshold: 4.5e+9
    weight: 2
  - name: "DiskUsage"
    query_tpl: "node_filesystem_avail_bytes{mountpoint='/'}"
    operator: "<"
    threshold: 1e+12  # 1TB - almost guaranteed to trigger
    weight: 2
  - name: "CPUUsage" 
    query_tpl: "100 - (avg(rate(node_cpu_seconds_total{mode='idle'}[1m])) * 100)"
    operator: ">"
    threshold: 0.1  # 0.1% CPU - should trigger with any activity
    weight: 1