---
# Enhanced Service Configuration for Node/System Monitoring

# Service Metadata
name: "node"
description: "System-level monitoring for Linux nodes and infrastructure"
version: "1.0"
tags: ["infrastructure", "system", "node", "linux"]
maintainer: "infrastructure-team@company.com"

# Alert Matching
alert_pattern: "node"
severity_levels: ["warning", "critical"]

# Data Sources
data_sources:
  elasticsearch:
    index_pattern: "${ES_INDEX_PATTERN:-fluentbit-*}"
    time_range_minutes: 20
    scan_limit: 1000
    namespace_filter: "kube-system"
    required_fields: ["@timestamp", "log", "kubernetes.container_name"]
  
  log_file: "/var/log/syslog"

# Symptom Detection
log_patterns:
  - name: "systemd_service_restart"
    description: "SystemD service restarts"
    regex: "systemd\\[1\\]: Starting"
    severity: "warning"
    
  - name: "kernel_error"
    description: "Kernel error messages"
    regex: "(?i)kernel.*error|kernel.*panic|oops"
    severity: "critical"
    
  - name: "disk_full"
    description: "Disk space warnings"
    regex: "(?i)no space left|disk.*full|filesystem.*full"
    severity: "critical"
    
  - name: "oom_killer"
    description: "Out of memory killer events"
    regex: "(?i)out of memory|oom-kill|killed process"
    severity: "critical"
    
  - name: "network_interface_down"
    description: "Network interface down events"
    regex: "(?i)link.*down|interface.*down|network.*unreachable"
    severity: "warning"

# Metrics Monitoring
metrics:
  - name: "NodeUp"
    description: "Node exporter availability"
    query_tpl: 'up{job="node-exporter"}'
    operator: "<"
    threshold: 1
    weight: 10
    unit: "boolean"
    
  - name: "NodeCPUUsage"
    description: "Node CPU utilization percentage"
    query_tpl: '100 - (avg(rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)'
    operator: ">"
    threshold: 85.0
    weight: 7
    unit: "percentage"
    
  - name: "NodeMemoryUsage"
    description: "Node memory utilization percentage"
    query_tpl: '(1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100'
    operator: ">"
    threshold: 90.0
    weight: 8
    unit: "percentage"
    
  - name: "NodeDiskUsage"
    description: "Node disk utilization percentage"
    query_tpl: '100 - ((node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"}) * 100)'
    operator: ">"
    threshold: 85.0
    weight: 6
    unit: "percentage"

# LLM Analysis Context
analysis_context:
  service_type: "infrastructure_node"
  criticality: "high"
  common_causes:
    - "resource_exhaustion"
    - "hardware_failure"
    - "kernel_issues"
    - "network_connectivity_problems"
    - "disk_space_issues"
  escalation_path: "infrastructure-team → system-admin → hardware-team"