services:
  hotrod:
    log_file: /home/priyanjith/copilot-stack/hotrod.log
    metrics:
      - name: HotrodTraffic
        query_tpl: sum(hotrod_http_requests_total)
        operator: ">"
        threshold: 50
        weight: 1

  node:
    log_file: /var/log/syslog
    metrics:
      - name: RAMUsage
        query_tpl: node_memory_Active_bytes
        operator: ">"
        threshold: 4.5e+9
        weight: 2
